apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recsys.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env.public }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}