{{- if .Values.env.private }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "recsys.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "recsys.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- range $key, $value := .Values.env.private }}
    {{ $key }}: {{ $value }}
    {{- end }}
  template:
    metadata:
      name: {{ include "recsys.fullname" . }}-secrets
{{- end }}